---
- hosts: 127.0.0.1
  user: root

  tasks:
  - include_vars: 
     file: users.yml
     name: users

  - name: Add users |create users, shells, homedirs, 
    user: name={{ item.username }} shell={{ item.shell }} createhome={{ item.createhome }} uid={{ item.uid }} group={{item.group}} 
    with_items: '{{ users }}'
